# Generated by Django 5.2.16 on 2026-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(related_name='variants', to='products.attributevalue'),
        ),
    ]
