# Generated by Django 5.2.16 on 2026-08-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_idempotency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='unpaid', max_length=20),
        ),
    ]
