# Generated by Django 5.2.16 on 2026-08-07 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_checkout_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
