# Generated by Django 5.2.16 on 2026-08-07 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_checkout_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
